### ISSUE TITLE
Check schedule

### ISSUE THREAD

**Issue by dpshelio** [UCL/2022-09-19-UCL-DaSH#1]
@mary-tziraki @tdveale  @sabaferdous12 Could you check the schedule on the website and change the file at `_includes/swc/schedule.html` as you think it's needed.

Open a Pull request with your suggested changes.

**Comment by mary-tziraki** [comment]
I have made some changes to the schedule.html to include more analytic description of the courses during the IDEAS day.
Please let me know if you need to change it.
Thank you

**Comment by dpshelio** [comment]
@mary-tziraki  - it's a bit too much. We don't need to give that many details and granularity between the hours. Set an appropriate title for each half-day that is meaningful and attractive. (Also, there are some typos).
I'm going to protect the `gh-pages`, please, create a Pull-Request for new changes to be incorporated.
