### ISSUE TITLE
Workshop registration page

### ISSUE THREAD

**Issue by dpshelio** [UCL/2022-09-19-UCL-DaSH#3]
The workshop registration could be done via Eventbrite (draft created already under RSDG account) – [draft event page](https://www.eventbrite.co.uk/e/396993747987). However, since this event is a paid event, we would need a two steps registration (one for the event and another for the payment). This won't be good as the Eventbrite page will say it's free when it's not.
Once the payment platform is set up, we need to find out whether we can use that as a registration platform.
If that page works, then we need to change a bit the code at [`index.md`](https://github.com/UCL/2022-09-19-UCL-DaSH/blob/gh-pages/index.md) similar to what's shown for Eventbrite between lines 77 and 87.

**Comment by hheaven1** [comment]
I have sent the completed form this morning for setting up an online payment.  Unfortunately my usual contact is on annual leave until next week but I have marked it as urgent and hope another member of the team can help.

UCL online stores will automatically send the name and email address of the person making the payment.  Additional information such as dietary requirements and consent for holding their contact details etc can be sought afterwards.  

Once the 30 places have been filled, then nobody else will be able to make a payment.  Therefore, UCL online stores cannot be used for a waiting list.  As a suggestion, maybe just mention in your advertising that if there are no remaining places available when attempting to make payment, to contact ... and be added to a waiting list.

**Comment by hheaven1** [comment]
Just remembered that there is an option to add questions to the online payments.  I have requested that the following is added:
Do you have any dietary requirements?  If yes, please provide details
Are you happy for us to keep your contact details for future events that may be of interest?

Anything else to be added?

I haven't added questions before so not sure if it's still possible but will keep you up to date.

**Comment by dtwwwc1e** [comment]
thanks for the update @hheaven1

**Comment by hheaven1** [comment]
[Online payment set up](https://onlinestore.ucl.ac.uk/product-catalogue/faculty-of-life-sciences-c08/division-of-biosciences-d09/d09-dash-software-carpentry-workshop)

**Comment by dpshelio** [comment]
I'll set a registration button on the workshop website that points to the Online Store page next week.

**Comment by hheaven1** [comment]
First payment received.
